export * from "./AboutPage";
export * from "./ArticlePage";
export * from "./EmployeePage";
export * from "./FaqPage";
export * from "./HomePage";
export * from "./HotlinePage";
export * from "./NewsPage";
export * from "./NotFoundPage";
export * from "./VacanciesPage";
